# Generated by Django 2.1.15 on 2020-04-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NgoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATE_UT', models.CharField(max_length=200)),
                ('SPECIFIC_LOCATION', models.CharField(max_length=200)),
                ('TARGET_GROUPS', models.CharField(max_length=200)),
                ('TYPE_OF_BENEFIT', models.CharField(max_length=200)),
                ('ORGANIZATION', models.CharField(max_length=200)),
                ('INITIATIVE', models.CharField(max_length=200)),
                ('WEBSITE', models.CharField(max_length=200)),
                ('DONATION_LINK', models.CharField(max_length=200)),
                ('DONATION_INFO', models.CharField(max_length=200)),
                ('FOREIGN_DONATION', models.CharField(max_length=200)),
                ('INFO', models.CharField(max_length=200)),
            ],
        ),
    ]
