# Generated by Django 2.1.15 on 2020-04-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NgoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOCATION', models.CharField(max_length=200)),
                ('TARGET_GROUPS', models.CharField(max_length=200)),
                ('ORGANIZATION', models.CharField(max_length=200)),
                ('TYPE_OF_BENEFIT', models.CharField(max_length=200)),
                ('WHAT_WILL_BE_PROVIDED', models.CharField(max_length=200)),
                ('DONATION_LINKS_INFO', models.CharField(max_length=200)),
                ('Exemptions', models.CharField(max_length=200)),
            ],
        ),
    ]
